# Generated by Django 2.0.2 on 2018-02-28 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First_name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last_name')),
                ('type_card', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('americanexpress', 'AmericanExpress'), ('maestro', 'Maestro'), ('discover', 'Discover')], max_length=20, verbose_name='Type_Card')),
                ('number_card', models.CharField(max_length=20, verbose_name='Number_Card')),
                ('cod_security', models.CharField(max_length=4, verbose_name='Code_Security')),
                ('date_expiration', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
