# Generated by Django 2.0.2 on 2018-03-08 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180305_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='profile_420', verbose_name='Image')),
                ('like', models.IntegerField(default=0, verbose_name='weedy-like')),
                ('state', models.CharField(max_length=255, verbose_name='State_image')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitud_image')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longitud_image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ImageProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_profile', models.ImageField(max_length=255, upload_to='profile', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='count_image',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='imageprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_image_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
