# Generated by Django 2.0.2 on 2018-03-19 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180308_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image', models.IntegerField(blank=True, null=True, verbose_name='Image_id')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('like', models.IntegerField(default=0, verbose_name='weedy-like')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State_image')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitud_image')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longitud_image')),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TermsCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='match_sex',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], default='Otro', max_length=10, null=True, verbose_name='Match_sex'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], default='Otro', max_length=10, null=True, verbose_name='Type_sex'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='publicfeed',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_image_feed', to=settings.AUTH_USER_MODEL),
        ),
    ]
