# Generated by Django 2.0.2 on 2018-03-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_add_group_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='typeUser',
        ),
    ]
