# Generated by Django 2.0.2 on 2018-03-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_remove_user_typeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(blank=True, null=True, verbose_name='user_id')),
                ('id_public_feed', models.IntegerField(blank=True, null=True, verbose_name='public_feed_id')),
                ('like', models.BooleanField(default=False)),
            ],
        ),
    ]
