# Generated by Django 2.0.2 on 2018-03-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_likeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distance',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Distance'),
        ),
    ]
